name: "track"
backend: "python"
max_batch_size: 0

input [
  { name: "FRAME", data_type: TYPE_UINT8, dims: [ -1 ] },
  { name: "FRAME_ID", data_type: TYPE_INT32, dims: [ 1 ] },
  { name: "INPUT_COUNT", data_type: TYPE_INT32, dims: [ 1 ] }
]

output [
  { name: "OUTPUT_COUNT", data_type: TYPE_INT32, dims: [ 1 ] },
  { name: "LATENCY_MS", data_type: TYPE_FP32, dims: [ 1 ] }
]

instance_group [
  { count: 2, kind: KIND_CPU }
]
